Please test: Update chat badge and .gitignore
adafruit/cookiecutter-adafruit-circuitpython pull request #181
Opened 2022-04-21 16:49 UTC by kattni

Updating to Adafruit Discord chat badge for Adafruit bundle only.

Updated the top-level cookiecutter .gitignore to match the globally updated .gitignore, with a couple of extras from the original that look cookiecutter-specific.

Please test that this generates properly before merging. Thanks!

2022-04-21 19:36 UTC, askpatrickw reviewed
I tested this and one thing I noticed was in the community version there is an extra blank link (see image) looks fine in adafruit version.

![image](https://user-images.githubusercontent.com/4002194/164539228-481895d3-8357-4ab3-84fd-14041523c9e2.png)

2022-04-21 19:38 UTC, kattni commented
@askpatrickw Hmm. Any idea how to resolve that?

2022-04-21 19:44 UTC, askpatrickw commented
I think the syntax is to use `{%-` and\or `-%}` like in these lines:

https://github.com/adafruit/cookiecutter-adafruit-circuitpython/blob/main/%7B%7B%20cookiecutter%20and%20'tmp_repo'%20%7D%7D/%7B%25%20if%20cookiecutter.library_prefix%20%25%7D%7B%7B%20cookiecutter.library_prefix%20%7C%20lower%20%7C%20replace(%22%20%22%2C%20%22_%22)%20%7D%7D_%7B%25%20endif%20%25%7D%7B%7B%20cookiecutter.library_name%20%7C%20lower%20%7C%20replace(%22%20%22%2C%20%22_%22)%20%7D%7D.py#L39

2022-04-21 20:59 UTC, kattni commented
@askpatrickw I'm unclear on exactly how to adapt this. I asked Tim about it on Discord and he thinks it might be the following change in the `endif`:
```
{%- if cookiecutter.target_bundle == 'Adafruit' %}
.. image:: https://github.com/adafruit/Adafruit_CircuitPython_Bundle/blob/main/badges/adafruit_discord.svg
{%- else %}
.. image:: https://img.shields.io/discord/327254708534116352.svg
{%- endif %}
```
If that's not it, can you clarify? There are a lot of options in the code you linked, and I'm not sure exactly what is doing what.

2022-04-21 21:48 UTC, askpatrickw requested changes
@kattni  I'm not 100% this is correct, but I think its the best thing to try first.

2022-04-21 21:48 UTC, askpatrickw commented on {{ cookiecutter and 'tmp_repo' }}/README.rst
> +{%- if cookiecutter.target_bundle == 'Adafruit' %}
```suggestion
{%- if cookiecutter.target_bundle == 'Adafruit' -%}
```

2022-04-21 21:48 UTC, askpatrickw commented on {{ cookiecutter and 'tmp_repo' }}/README.rst
> +{%- else %}
```suggestion
{%- else -%}
```

2022-04-21 21:48 UTC, askpatrickw commented on {{ cookiecutter and 'tmp_repo' }}/README.rst
> +{% endif %}
```suggestion
{%- endif -%}
```

2022-04-21 22:18 UTC, askpatrickw commented
Nope... ;-)
@kattni, I have some time, I'll look at this in a bit and give you the fix.

2022-04-21 22:19 UTC, kattni commented
@askpatrickw Thank you so much!

2022-04-21 22:49 UTC, askpatrickw commented
@kattni  OK I tested that and commited into your PR.
@FoamyGuy  if you want to be the final reviewer, that would be great.

2022-04-21 22:55 UTC, kattni commented
@askpatrickw Thank you again for all your help here! I really appreciate it.

2022-04-22 01:00 UTC, FoamyGuy approved these changes
Looks good to me. Tested all 3 bundle types successfully. All appear correct to me. I also pushed one of the Adafruit bundle tests to a repo in my github account to double check that it will render the badge correctly and confirmed that it does.

2022-04-22 01:01 UTC, merged